// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

package cmdref

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
	"github.com/spf13/pflag"
	"go.yaml.in/yaml/v2"
)

func NewCmd(parentCmd *cobra.Command) *cobra.Command {
	var format string
	cmd := &cobra.Command{
		Use:    "cmdref [output directory]",
		Short:  fmt.Sprintf("Generate command reference for %s to given output directory", parentCmd.Name()),
		Args:   cobra.ExactArgs(1),
		Hidden: true,
		Run: func(cmd *cobra.Command, args []string) {

			if format == "flags-yaml" {
				if err := genFlagNameYAML(parentCmd, args[0]); err != nil {
					fmt.Println(err)
					os.Exit(1)
				}
				return
			}
			genMarkdown(parentCmd, args[0])
		},
	}

	cmd.Flags().StringVar(&format, "format", "markdown",
		"output format (markdown|flags-yaml)")

	return cmd
}

type FlagEntry struct {
	Name    string `yaml:"name"`
	Default string `yaml:"default"`
	Usage   string `yaml:"usage"`
}

func genFlagNameYAML(cmd *cobra.Command, dir string) error {

	var flags []FlagEntry
	cmd.Flags().VisitAll(func(f *pflag.Flag) {
		flags = append(flags, FlagEntry{
			Name:    f.Name,
			Default: f.DefValue,
			Usage:   f.Usage,
		})
	})

	data, err := yaml.Marshal(flags)
	if err != nil {
		return err
	}
	filePath := filepath.Join(dir, cmd.Name()+"_flags.yaml")
	return os.WriteFile(filePath, data, 0644)
}

func genMarkdown(parentCmd *cobra.Command, cmdRefDir string) {
	// Remove the line 'Auto generated by spf13/cobra on ...'
	parentCmd.DisableAutoGenTag = true
	if err := doc.GenMarkdownTreeCustom(parentCmd, cmdRefDir, filePrepend(parentCmd.Name()), linkHandler); err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
}

func linkHandler(s string) string {
	return s
}

func filePrepend(parentCmdName string) func(string) string {
	// Prepend a HTML comment that this file is autogenerated. So that
	// users are warned before fixing issues in the Markdown files.  Should
	// never show up on the web.
	return func(string) string {
		return fmt.Sprintf("<!-- This file was autogenerated via %s cmdref, do not edit manually-->\n\n", parentCmdName)
	}
}
